favicon: /img/KZ-AI.png
# Change to your profile picture
avatar: /img/KZ.JPG
# if author sets in hexo_config, this string doesn't work
author: 'Keyan Zhai'
author_bio: "Robotics MSE'23 @ University of Pennsylvania"

since: 2023

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  Publications: /Publications/
  Projects: /Projects/

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: False
social_links:
  # fab fa-github: https://github.com/keyanzhai
  # fab fa-linkedin: https://www.linkedin.com/in/keyanzhai/

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Email: mailto:keyanzhai3@gmail.com || fas fa-envelope
  LinkedIn: https://www.linkedin.com/in/keyanzhai/ || fab fa-linkedin
  Github: https://github.com/keyanzhai || fab fa-github
  Google Scholar: https://scholar.google.com/citations?user=F3jHhSoAAAAJ&hl=en&oi=ao || fas fa-graduation-cap
  ORCID: https://orcid.org/0009-0008-4719-8575 || fab fa-orcid
  Youtube: https://youtube.com/@KZ-qz7kd || fab fa-youtube

# CV download link
cv_dl:
  enable: true
  dir: /attaches/CV_KeyanZhai.pdf
  description: CV

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: True

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js